### ISSUE TITLE
clone repo using git bash

### ISSUE THREAD

**Issue by kbrannan** [PythonCodersOR/plot_diel_do_qual2kw_output#3]
Use this steps:

1. open a DOS command line window (enter 'cmd' in the windows search box)
2. goto your c: drive
3. create a folder named 'junk'
4. cd to junk
5. run git bash from command line using following command:
    start "" "%PROGRAMFILES%\Git\bin\sh.exe" --login
6. clone the remote repo using command
    git clone https://github.com/PythonCodersOR/plot_diel_do_qual2kw_output
7. change to the local repo folder using command:
    cd part_distribution_plots
8. Tell me what brnaches are in your local repo. Get the local branches using command:
    git branch

Reply to this issue with the answer to step 8. If you encounter any diffficulties, send me a reply to this issue saying which step gave you the difficulty and copy-paste any error info provided

Have fun!!!
Kevin

**Comment by DEQdsobota** [comment]
I'm having a problem with steps 7 and 8:

dsobota@WQ101477-DSOBOT MINGW64 /c/junk
$ cd part_distribution_plot
bash: cd: part_distribution_plot: No such file or directory

dsobota@WQ101477-DSOBOT MINGW64 /c/junk
$ git branch
fatal: Not a git repository (or any of the parent directories): .git

**Comment by kbrannan** [comment]
Use this steps:

1. open a DOS command line window (enter 'cmd' in the windows search box)
2.  goto your c: drive
3. create a folder named 'junk'
4. cd to junk
5. run git bash from command line using following command:
    start "" "%PROGRAMFILES%\Git\bin\sh.exe" --login
6. clone the remote repo using command
    git clone https://github.com/PythonCodersOR/plot_diel_do_qual2kw_output
7. change to the local repo folder using command:
    cd plot_diel_do_qual2kw_output  (**ooops, my bad**)
8. Tell me what brnaches are in your local repo. Get the local branches using command:
    git branch

Reply to this issue with the answer to step 8. If you encounter any diffficulties, send me a reply to this issue saying which step gave you the difficulty and copy-paste any error info provided

Have **more** fun!!!
Kevin

**Comment by DEQdsobota** [comment]
* master

**Comment by kbrannan** [comment]
Nice!!!!!

Take a look at the GitHub repo branches:
https://github.com/PythonCodersOR/plot_diel_do_qual2kw_output/branches

Is there a difference?

**Comment by DEQdsobota** [comment]
My branch, an active branch, is start00

**Comment by kbrannan** [comment]
In git in your local copy of the repo type command:
git branch -a

Can you see start00 somewhere?

**Comment by DEQdsobota** [comment]
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/master
  remotes/origin/start00

**Comment by kbrannan** [comment]
Nice!!!
In git in your local copy of the repo type command:
git checkout start00

Then type:
git branch

Can you see start00?

**Comment by DEQdsobota** [comment]
master
* start00

**Comment by kbrannan** [comment]
Nice!!!!

So what you did when you cloned the remote repo, you don't aitomatically get all the branches, casue why would you want that???? You only want the latest stable version (which should be the master branch). However, you can get a copy fo a remote branch locally if you check it out in your local repo.

This is what happend through some of the GUIs like RStudio, but I think it is good to do it yourself so you know what is going on.
